export const GET_ALL_ORDERS_ADMIN_REQUEST = 'GET_ALL_ORDERS_ADMIN_REQUEST'
export const GET_ALL_ORDERS_ADMIN_SUCCESS = 'GET_ALL_ORDERS_ADMIN_SUCCESS'
export const GET_ALL_ORDERS_ADMIN_FAIL = 'GET_ALL_ORDERS_ADMIN_FAIL'